server:
  port: 8082

spring:
  application:
    name: todo-service
  boot:
    admin:
      client:
        url: http://localhost:9090  # URL del Admin Server
        instance:
          prefer-ip: true
          service-host-type: ip     

  datasource:
    url: jdbc:mysql://localhost:3306/tareasmicroservicio1?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
