server:
  port: 8081

spring:
  application:
    name: user-service
    # NUEVA CONFIGURACIÓN para Spring Boot Admin
  boot:
    admin:
      client:
        url: http://localhost:9090  # URL del Admin Server
        instance:
          prefer-ip: true
          service-host-type: ip  

  datasource:
    url: jdbc:mysql://localhost:3306/userdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: tu_password
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: update # crea automáticamente tablas y columnas según tus entidades
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
